version: '3.9'

services:
  walletassnginx:
    container_name: walletass-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '8101:80'
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - walletassapp
    networks:
      - walletass-network


  walletassapp:
    container_name: walletass-app
    build:
      context: .
      dockerfile: Dockerfile
    image: php8.2-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - walletass-network

  walletasscom:
    container_name: walletass-com
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - walletass-network

networks:
  walletass-network:
    external:
        name: server_webserver-network
